### ISSUE TITLE
Normalize NistP256 signature

### ISSUE THREAD

**Issue by x87-va** [RustCrypto/signatures#341]
I'm trying to convert signature to low S, but got compilation error.

Dependencies used:
```toml
ecdsa           = "0.12"
elliptic-curve  = "0.10"
p256            = "0.9"
```

Error:
```rust
let signature = Signature::<p256::NistP256>::from_der(&data)?;
signature.normalize_s()?;
^^^^^^^^^^^ the trait `NormalizeLow` is not implemented for `Scalar`
```

How to fix it? What exact type need to implement trait NormalizeLow?
